//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by sdk_demo_new.rc
//

#define IDI_ICON_LOGO						123
#define IDXML_MAINFRAME_UI					124
#define IDXML_LOGINFRAME_UI					125
#define IDXML_LOGINUSER_METTINGFRAME_UI		126
#define IDXML_RESTAPI_MEETINGFRAME_UI		127
#define IDXML_SCHEDULE_MEETINGFRAME_UI      128
#define IDXML_SETTINGSFRAME_UI         130
#define IDXML_TOOLBAR_BOTTOM_UI				129
#define IDXML_MEETING_CHAT_FRAME_UI				131
#define IDXML_JOIN_MEETING_FRAME_UI				132
#define IDXML_ARROW_BAR_FRAME_UI				133
#define IDXML_MEETING_PARTICIPANT_LIST_UI		134
#define IDXML_MEETING_PARTICIPANT_WINDOW		135
#define IDXML_SHARE_SELECTAPP_UI				136
// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NO_MFC					130
#define _APS_NEXT_RESOURCE_VALUE	129
#define _APS_NEXT_COMMAND_VALUE		32771
#define _APS_NEXT_CONTROL_VALUE		1000
#define _APS_NEXT_SYMED_VALUE		110
#endif
#endif
