//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by sdk_demo_new.rc
//

#define IDI_ICON_LOGO						123
#define IDXML_MAINFRAME_UI					124
#define IDXML_LOGINFRAME_UI					125
#define IDXML_LOGINUSER_METTINGFRAME_UI		126
#define IDXML_RESTAPI_MEETINGFRAME_UI		127
#define IDXML_SCHEDULE_MEETINGFRAME_UI      128
#define IDXML_SETTINGSFRAME_UI         130
#define IDXML_TOOLBAR_BOTTOM_UI				129
#define IDXML_MEETING_CHAT_FRAME_UI				131
#define IDXML_JOIN_MEETING_FRAME_UI				132
#define IDXML_ARROW_BAR_FRAME_UI				133
#define IDXML_MEETING_PARTICIPANT_LIST_UI		134
#define IDXML_MEETING_PARTICIPANT_WINDOW		135
#define IDXML_SHARE_SELECTAPP_UI				136
#define IDXML_MORE_BUTTON_MENU_UI				137
#define IDXML_MEETING_CLOSE_CAPTION_UI			138
#define IDXML_CAMERA_CONTROL_UI                 139
#define IDXML_MEETING_INVITATION_UI				140
#define IDXML_SCHEDULE_EDIT_DIAL_IN_COUNTRY_UI  141
#define IDXML_SHARE_TOOLBAR_WINDOW_UI           142
#define IDXML_VIEW_OPTIONS_WINDOW_UI            143
#define IDXML_ANNOTATE_BAR_WINDOW_UI            144
#define IDXML_ANNOTATE_FORMAT_WINDOW_UI         145
#define IDXML_ANNOTATE_DRAW_WINDOW_UI           146
#define IDXML_ANNOTATE_STAMP_WINDOW_UI          147
#define IDXML_ANNOTATE_SPOLIGHT_WINDOW_UI       148
#define IDXML_ANNOTATE_CLEAR_WINDOW_UI          149
// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NO_MFC					130
#define _APS_NEXT_RESOURCE_VALUE	129
#define _APS_NEXT_COMMAND_VALUE		32771
#define _APS_NEXT_CONTROL_VALUE		1000
#define _APS_NEXT_SYMED_VALUE		110
#endif
#endif
